package day22_arrayList;

import java.lang.String; // this was needed to use String class, however, any class from java lang class is imported implicitly
//import java.lang.Double; this is autogenerated so not needed.

public class WrapperClassesIntro {

    public static void main(String[] args) {

        // String also comes from lang package and imported automatically

        String str = "Java";

        int a = 10; // primitive we can assign integer
        // this won't be supported in some DS.

        Integer a2 = 10; // Integer. non-primitive. Wrapper class.
        // you need to use Integer for most DS.


        System.out.println("---");

        int b1 = 100;

        double c1 = b1; // these are possible
        long c2 = b1; // possible

        Integer b2 = b1; // autobox

        // Long b3 = b1; // not possible. they are only loyal to the own primitive
        // Double b4 = b1; // not possible



        char ch = 'A';
        Character ch2 = ch; // Autoboxing

        double d1 = 5.5;
        Double d2 = d1; // Autoboxing

        System.out.println("---");

        Integer n1 = 20;
        // unboxing:
        int n2 = n1;
        long n3 = n1;
        double n4 = n1;

        Character e1 = 'C';
        char e2 = e1; // unboxing

//        int e3 = e1;
//        long e4 = e1;









    }
}
